name: healsense
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  badges: ^2.0.3
  cupertino_icons: ^1.0.5
  drift: ^2.3.0
  equatable: ^2.0.5
  fimber: ^0.6.6
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg_provider: ^1.0.3
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  go_router: ^5.2.4
  google_maps_flutter: ^2.2.2
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  nil: ^1.1.1
  path: ^1.8.2
  path_provider: ^2.0.11
  riverpod_annotation: ^1.0.6
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sqlite3_flutter_libs: ^0.5.12
  timezone: ^0.9.0
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.3.3
  flutter_config: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/logo.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sliders/
    - assets/images/pharmacy_illustrations/
    - assets/icons/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
